# Generated by Django 4.2.5 on 2023-09-23 22:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Instituicao',
            fields=[
                ('nome', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('foto_instituicao', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Moedas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='CarteiraCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agencia', models.IntegerField()),
                ('conta', models.IntegerField()),
                ('login_Instituicao', models.CharField(max_length=50)),
                ('senha_Instituicao', models.CharField(max_length=20)),
                ('saldo', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('saldo_drex', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('instituicao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TecHub.instituicao')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
