# Generated by Django 4.2.5 on 2023-09-25 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TecHub', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NavItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('url', models.CharField(max_length=100)),
                ('icone', models.CharField(max_length=50)),
            ],
        ),
    ]
