# Generated by Django 4.2.5 on 2023-09-25 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TecHub', '0002_navitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='navitem',
            name='icone',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='navitem',
            name='nome',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='navitem',
            name='url',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
