# Generated by Django 4.2.5 on 2023-09-29 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TecHub', '0003_infoclienteinstituicao_instituicao'),
    ]

    operations = [
        migrations.AddField(
            model_name='navitem',
            name='pagina',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
