# Generated by Django 4.2.5 on 2023-09-26 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TecHub', '0003_alter_navitem_icone_alter_navitem_nome_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='navitem',
            name='icone',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
