# Generated by Django 4.2.5 on 2023-09-26 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TecHub', '0004_alter_navitem_icone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='navitem',
            name='icone',
            field=models.TextField(max_length=500, null=True),
        ),
    ]
